
systemUrl: 192.168.153.129

server:
  port: 8080

spring:
  datasource:
    #mysql
    username: root
    password: root
    url: jdbc:mysql://${systemUrl}:3306/bs?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

    #redis
  redis:
    #集群配置
    cluster:
      nodes:
        - ${systemUrl}:7001
        - ${systemUrl}:7002
        - ${systemUrl}:7003
        - ${systemUrl}:7004
        - ${systemUrl}:7005
    #连接池
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    # 连接超时时间（毫秒）
    timeout: 3000ms



#mybatis-plus
mybatis-plus:
  #   type-aliases-package: com.itheima.mp.domain.po
  global-config:
    db-config:
      id-type: AUTO # 全局id类型为自增长

  mapper-locations:
    - "classpath:/mapper/**/*.xml"
    - "classpath:/mapper/*.xml"

#日志配置
logging:
  #配置文件位置
  config: classpath:logback-spring.xml
  #
  level:
    #顶层root级别
    root: info
    #包设置对应级别
#    com:
#      springboot: debug


    #  文件配置路径
    #  file:
    #    name: ./log/materialized.log
    #    path: ./log/

    #   轮转配置
    #   max-file-size: 256MB
    #   max-history: 20

    #！ 也可以在配置文件中粗略定义输出格式
    # pattern:
    #  console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    #  file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: werbth #JWT加解密使用 非对称加密密匙
  expiration: 14400 #JWT的超期限时间(60*60*4)-秒数
  tokenHead: Bearer  #JWT负载中拿到开头

redis_time:
  login: 40  #登录信息默认保存实践 min
  used:  5   # 一般查询信息默认保存时间 min